export { default as About } from './About/About'
export { default as Home } from './Home/Home'
export { default as Settings } from './Settings/Settings'
export { default as SideMenu } from './SideMenu/SideMenu'
export { default as Welcome } from './Welcome/Welcome'
