export default {
  light: 'NunitoSans-Light',
  regular: 'NunitoSans-Regular',
  bold: 'NunitoSans-ExtraBold',
  text: 12,
  textLineHeight: 16,
  body: 14,
  bodyLineHeight: 22,
  headline4: 18,
  headline4LineHeight: 26,
  headline3: 20,
  headline3LineHeight: 34,
  headline2: 30,
  headline2LineHeight: 44,
  headline1: 36,
  headline1LineHeight: 52,
}
