import { StyleSheet } from 'react-native'

export default StyleSheet.create({
  marXs: { marginHorizontal: 4, marginVertical: 4 },
  marSm: { marginHorizontal: 8, marginVertical: 8 },
  mar: { marginHorizontal: 16, marginVertical: 16 },
  marMd: { marginHorizontal: 24, marginVertical: 24 },
  marLg: { marginHorizontal: 32, marginVertical: 32 },
  marTopXs: { marginTop: 4 },
  marTopSm: { marginTop: 8 },
  marTop: { marginTop: 16 },
  marTopMd: { marginTop: 24 },
  marTopLg: { marginTop: 32 },
  marLeftXs: { marginLeft: 4 },
  marLeftSm: { marginLeft: 8 },
  marLeft: { marginLeft: 16 },
  marLeftMd: { marginLeft: 24 },
  marLeftLg: { marginLeft: 32 },
  marRightXs: { marginRight: 4 },
  marRightSm: { marginRight: 8 },
  marRight: { marginRight: 16 },
  marRightMd: { marginRight: 24 },
  marRightLg: { marginRight: 32 },
  marBotXs: { marginBottom: 4 },
  marBotSm: { marginBottom: 8 },
  marBot: { marginBottom: 16 },
  marBotMd: { marginBottom: 24 },
  marBotLg: { marginBottom: 32 },
  marVertXs: { marginVertical: 4 },
  marVertSm: { marginVertical: 8 },
  marVert: { marginVertical: 16 },
  marVertMd: { marginVertical: 24 },
  marVertLg: { marginVertical: 32 },
  marHorXs: { marginHorizontal: 4 },
  marHorSm: { marginHorizontal: 8 },
  marHor: { marginHorizontal: 16 },
  marHorMd: { marginHorizontal: 24 },
  marHorLg: { marginHorizontal: 32 },

  padXs: { marginHorizontal: 4, marginVertical: 4 },
  padSm: { marginHorizontal: 8, marginVertical: 8 },
  pad: { marginHorizontal: 16, marginVertical: 16 },
  padMd: { marginHorizontal: 24, marginVertical: 24 },
  padLg: { marginHorizontal: 32, marginVertical: 32 },
  padTopXs: { paddingTop: 4 },
  padTopSm: { paddingTop: 8 },
  padTop: { paddingTop: 16 },
  padTopMd: { paddingTop: 24 },
  padTopLg: { paddingTop: 32 },
  padLeftXs: { paddingLeft: 4 },
  padLeftSm: { paddingLeft: 8 },
  padLeft: { paddingLeft: 16 },
  padLeftMd: { paddingLeft: 24 },
  padLeftLg: { paddingLeft: 32 },
  padRightXs: { paddingRight: 4 },
  padRightSm: { paddingRight: 8 },
  padRight: { paddingRight: 16 },
  padRightMd: { paddingRight: 24 },
  padRightLg: { paddingRight: 32 },
  padBotXs: { paddingBottom: 4 },
  padBotSm: { paddingBottom: 8 },
  padBot: { paddingBottom: 16 },
  padBotMd: { paddingBottom: 24 },
  padBotLg: { paddingBottom: 32 },
  padVertXs: { paddingVertical: 4 },
  padVertSm: { paddingVertical: 8 },
  padVert: { paddingVertical: 16 },
  padVertMd: { paddingVertical: 24 },
  padVertLg: { paddingVertical: 32 },
  padHorXs: { paddingHorizontal: 4 },
  padHorSm: { paddingHorizontal: 8 },
  padHor: { paddingHorizontal: 16 },
  padHorMd: { paddingHorizontal: 24 },
  padHorLg: { paddingHorizontal: 32 },

  flex1: { flex: 1 },
  flex01: { flex: 0.1 },
  flex02: { flex: 0.2 },
  flex03: { flex: 0.3 },
  flex04: { flex: 0.4 },
  flex05: { flex: 0.5 },
  flex06: { flex: 0.6 },
  flex07: { flex: 0.7 },
  flex08: { flex: 0.8 },
  flex09: { flex: 0.9 },
  row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  col: { flexDirection: 'column' },
})
